//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  hero: Hero;
  heroConnection: HeroConnection;
  hero_card: Hero_Card;
  hero_cardConnection: Hero_CardConnection;
  mission: Mission;
  missionConnection: MissionConnection;
  what_we_do: What_We_Do;
  what_we_doConnection: What_We_DoConnection;
  events: Events;
  eventsConnection: EventsConnection;
  support: Support;
  supportConnection: SupportConnection;
  contact_intro: Contact_Intro;
  contact_introConnection: Contact_IntroConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  donation: Donation;
  donationConnection: DonationConnection;
  board: Board;
  boardConnection: BoardConnection;
  staff: Staff;
  staffConnection: StaffConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QueryHero_CardArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHero_CardConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Hero_CardFilter>;
};


export type QueryMissionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMissionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MissionFilter>;
};


export type QueryWhat_We_DoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWhat_We_DoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<What_We_DoFilter>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};


export type QuerySupportArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySupportConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SupportFilter>;
};


export type QueryContact_IntroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContact_IntroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Contact_IntroFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryDonationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDonationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DonationFilter>;
};


export type QueryBoardArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBoardConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BoardFilter>;
};


export type QueryStaffArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStaffConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StaffFilter>;
};

export type DocumentFilter = {
  hero?: InputMaybe<HeroFilter>;
  hero_card?: InputMaybe<Hero_CardFilter>;
  mission?: InputMaybe<MissionFilter>;
  what_we_do?: InputMaybe<What_We_DoFilter>;
  events?: InputMaybe<EventsFilter>;
  support?: InputMaybe<SupportFilter>;
  contact_intro?: InputMaybe<Contact_IntroFilter>;
  contact?: InputMaybe<ContactFilter>;
  donation?: InputMaybe<DonationFilter>;
  board?: InputMaybe<BoardFilter>;
  staff?: InputMaybe<StaffFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Hero | Hero_Card | Mission | What_We_Do | Events | Support | Contact_Intro | Contact | Donation | Board | Staff | Folder;

export type Hero = Node & Document & {
  __typename?: 'Hero';
  headline: Scalars['String']['output'];
  subheadline?: Maybe<Scalars['String']['output']>;
  cta_primary_text?: Maybe<Scalars['String']['output']>;
  cta_primary_link?: Maybe<Scalars['String']['output']>;
  cta_secondary_text?: Maybe<Scalars['String']['output']>;
  cta_secondary_link?: Maybe<Scalars['String']['output']>;
  hero_meta?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeroFilter = {
  headline?: InputMaybe<StringFilter>;
  subheadline?: InputMaybe<StringFilter>;
  cta_primary_text?: InputMaybe<StringFilter>;
  cta_primary_link?: InputMaybe<StringFilter>;
  cta_secondary_text?: InputMaybe<StringFilter>;
  cta_secondary_link?: InputMaybe<StringFilter>;
  hero_meta?: InputMaybe<StringFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type Hero_Card = Node & Document & {
  __typename?: 'Hero_card';
  title?: Maybe<Scalars['String']['output']>;
  date_label?: Maybe<Scalars['String']['output']>;
  time_label?: Maybe<Scalars['String']['output']>;
  location_label?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  image_alt?: Maybe<Scalars['String']['output']>;
  ticket_url?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Hero_CardFilter = {
  title?: InputMaybe<StringFilter>;
  date_label?: InputMaybe<StringFilter>;
  time_label?: InputMaybe<StringFilter>;
  location_label?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  image_alt?: InputMaybe<StringFilter>;
  ticket_url?: InputMaybe<StringFilter>;
};

export type Hero_CardConnectionEdges = {
  __typename?: 'Hero_cardConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero_Card>;
};

export type Hero_CardConnection = Connection & {
  __typename?: 'Hero_cardConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Hero_CardConnectionEdges>>>;
};

export type Mission = Node & Document & {
  __typename?: 'Mission';
  heading?: Maybe<Scalars['String']['output']>;
  body_1?: Maybe<Scalars['String']['output']>;
  body_2?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MissionFilter = {
  heading?: InputMaybe<StringFilter>;
  body_1?: InputMaybe<StringFilter>;
  body_2?: InputMaybe<StringFilter>;
};

export type MissionConnectionEdges = {
  __typename?: 'MissionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Mission>;
};

export type MissionConnection = Connection & {
  __typename?: 'MissionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MissionConnectionEdges>>>;
};

export type What_We_Do = Node & Document & {
  __typename?: 'What_we_do';
  heading?: Maybe<Scalars['String']['output']>;
  card_1_title?: Maybe<Scalars['String']['output']>;
  card_1_body?: Maybe<Scalars['String']['output']>;
  card_2_title?: Maybe<Scalars['String']['output']>;
  card_2_body?: Maybe<Scalars['String']['output']>;
  card_3_title?: Maybe<Scalars['String']['output']>;
  card_3_body?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type What_We_DoFilter = {
  heading?: InputMaybe<StringFilter>;
  card_1_title?: InputMaybe<StringFilter>;
  card_1_body?: InputMaybe<StringFilter>;
  card_2_title?: InputMaybe<StringFilter>;
  card_2_body?: InputMaybe<StringFilter>;
  card_3_title?: InputMaybe<StringFilter>;
  card_3_body?: InputMaybe<StringFilter>;
};

export type What_We_DoConnectionEdges = {
  __typename?: 'What_we_doConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<What_We_Do>;
};

export type What_We_DoConnection = Connection & {
  __typename?: 'What_we_doConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<What_We_DoConnectionEdges>>>;
};

export type Events = Node & Document & {
  __typename?: 'Events';
  heading?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  bullet_1?: Maybe<Scalars['String']['output']>;
  bullet_2?: Maybe<Scalars['String']['output']>;
  bullet_3?: Maybe<Scalars['String']['output']>;
  footer_note?: Maybe<Scalars['String']['output']>;
  featured_card_title?: Maybe<Scalars['String']['output']>;
  featured_card_intro?: Maybe<Scalars['String']['output']>;
  featured_card_body?: Maybe<Scalars['String']['output']>;
  featured_card_wexler_note?: Maybe<Scalars['String']['output']>;
  featured_card_gofundme_label?: Maybe<Scalars['String']['output']>;
  featured_card_gofundme_url?: Maybe<Scalars['String']['output']>;
  featured_card_tickets_label?: Maybe<Scalars['String']['output']>;
  featured_card_tickets_url?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EventsFilter = {
  heading?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  bullet_1?: InputMaybe<StringFilter>;
  bullet_2?: InputMaybe<StringFilter>;
  bullet_3?: InputMaybe<StringFilter>;
  footer_note?: InputMaybe<StringFilter>;
  featured_card_title?: InputMaybe<StringFilter>;
  featured_card_intro?: InputMaybe<StringFilter>;
  featured_card_body?: InputMaybe<StringFilter>;
  featured_card_wexler_note?: InputMaybe<StringFilter>;
  featured_card_gofundme_label?: InputMaybe<StringFilter>;
  featured_card_gofundme_url?: InputMaybe<StringFilter>;
  featured_card_tickets_label?: InputMaybe<StringFilter>;
  featured_card_tickets_url?: InputMaybe<StringFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Support = Node & Document & {
  __typename?: 'Support';
  heading?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  bullet_1?: Maybe<Scalars['String']['output']>;
  bullet_2?: Maybe<Scalars['String']['output']>;
  bullet_3?: Maybe<Scalars['String']['output']>;
  bullet_4?: Maybe<Scalars['String']['output']>;
  card_title?: Maybe<Scalars['String']['output']>;
  card_body?: Maybe<Scalars['String']['output']>;
  card_link_label?: Maybe<Scalars['String']['output']>;
  card_link_url?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SupportFilter = {
  heading?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  bullet_1?: InputMaybe<StringFilter>;
  bullet_2?: InputMaybe<StringFilter>;
  bullet_3?: InputMaybe<StringFilter>;
  bullet_4?: InputMaybe<StringFilter>;
  card_title?: InputMaybe<StringFilter>;
  card_body?: InputMaybe<StringFilter>;
  card_link_label?: InputMaybe<StringFilter>;
  card_link_url?: InputMaybe<StringFilter>;
};

export type SupportConnectionEdges = {
  __typename?: 'SupportConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Support>;
};

export type SupportConnection = Connection & {
  __typename?: 'SupportConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SupportConnectionEdges>>>;
};

export type Contact_Intro = Node & Document & {
  __typename?: 'Contact_intro';
  heading?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Contact_IntroFilter = {
  heading?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
};

export type Contact_IntroConnectionEdges = {
  __typename?: 'Contact_introConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact_Intro>;
};

export type Contact_IntroConnection = Connection & {
  __typename?: 'Contact_introConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Contact_IntroConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  mailing_name?: Maybe<Scalars['String']['output']>;
  mailing_street?: Maybe<Scalars['String']['output']>;
  mailing_city?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  mailing_name?: InputMaybe<StringFilter>;
  mailing_street?: InputMaybe<StringFilter>;
  mailing_city?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Donation = Node & Document & {
  __typename?: 'Donation';
  url?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DonationFilter = {
  url?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type DonationConnectionEdges = {
  __typename?: 'DonationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Donation>;
};

export type DonationConnection = Connection & {
  __typename?: 'DonationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DonationConnectionEdges>>>;
};

export type BoardMembers = {
  __typename?: 'BoardMembers';
  name: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Board = Node & Document & {
  __typename?: 'Board';
  members?: Maybe<Array<Maybe<BoardMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BoardMembersFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type BoardFilter = {
  members?: InputMaybe<BoardMembersFilter>;
};

export type BoardConnectionEdges = {
  __typename?: 'BoardConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Board>;
};

export type BoardConnection = Connection & {
  __typename?: 'BoardConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BoardConnectionEdges>>>;
};

export type StaffMembers = {
  __typename?: 'StaffMembers';
  name: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Staff = Node & Document & {
  __typename?: 'Staff';
  members?: Maybe<Array<Maybe<StaffMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StaffMembersFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type StaffFilter = {
  members?: InputMaybe<StaffMembersFilter>;
};

export type StaffConnectionEdges = {
  __typename?: 'StaffConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Staff>;
};

export type StaffConnection = Connection & {
  __typename?: 'StaffConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StaffConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHero: Hero;
  createHero: Hero;
  updateHero_card: Hero_Card;
  createHero_card: Hero_Card;
  updateMission: Mission;
  createMission: Mission;
  updateWhat_we_do: What_We_Do;
  createWhat_we_do: What_We_Do;
  updateEvents: Events;
  createEvents: Events;
  updateSupport: Support;
  createSupport: Support;
  updateContact_intro: Contact_Intro;
  createContact_intro: Contact_Intro;
  updateContact: Contact;
  createContact: Contact;
  updateDonation: Donation;
  createDonation: Donation;
  updateBoard: Board;
  createBoard: Board;
  updateStaff: Staff;
  createStaff: Staff;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdateHero_CardArgs = {
  relativePath: Scalars['String']['input'];
  params: Hero_CardMutation;
};


export type MutationCreateHero_CardArgs = {
  relativePath: Scalars['String']['input'];
  params: Hero_CardMutation;
};


export type MutationUpdateMissionArgs = {
  relativePath: Scalars['String']['input'];
  params: MissionMutation;
};


export type MutationCreateMissionArgs = {
  relativePath: Scalars['String']['input'];
  params: MissionMutation;
};


export type MutationUpdateWhat_We_DoArgs = {
  relativePath: Scalars['String']['input'];
  params: What_We_DoMutation;
};


export type MutationCreateWhat_We_DoArgs = {
  relativePath: Scalars['String']['input'];
  params: What_We_DoMutation;
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationUpdateSupportArgs = {
  relativePath: Scalars['String']['input'];
  params: SupportMutation;
};


export type MutationCreateSupportArgs = {
  relativePath: Scalars['String']['input'];
  params: SupportMutation;
};


export type MutationUpdateContact_IntroArgs = {
  relativePath: Scalars['String']['input'];
  params: Contact_IntroMutation;
};


export type MutationCreateContact_IntroArgs = {
  relativePath: Scalars['String']['input'];
  params: Contact_IntroMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateDonationArgs = {
  relativePath: Scalars['String']['input'];
  params: DonationMutation;
};


export type MutationCreateDonationArgs = {
  relativePath: Scalars['String']['input'];
  params: DonationMutation;
};


export type MutationUpdateBoardArgs = {
  relativePath: Scalars['String']['input'];
  params: BoardMutation;
};


export type MutationCreateBoardArgs = {
  relativePath: Scalars['String']['input'];
  params: BoardMutation;
};


export type MutationUpdateStaffArgs = {
  relativePath: Scalars['String']['input'];
  params: StaffMutation;
};


export type MutationCreateStaffArgs = {
  relativePath: Scalars['String']['input'];
  params: StaffMutation;
};

export type DocumentUpdateMutation = {
  hero?: InputMaybe<HeroMutation>;
  hero_card?: InputMaybe<Hero_CardMutation>;
  mission?: InputMaybe<MissionMutation>;
  what_we_do?: InputMaybe<What_We_DoMutation>;
  events?: InputMaybe<EventsMutation>;
  support?: InputMaybe<SupportMutation>;
  contact_intro?: InputMaybe<Contact_IntroMutation>;
  contact?: InputMaybe<ContactMutation>;
  donation?: InputMaybe<DonationMutation>;
  board?: InputMaybe<BoardMutation>;
  staff?: InputMaybe<StaffMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  hero?: InputMaybe<HeroMutation>;
  hero_card?: InputMaybe<Hero_CardMutation>;
  mission?: InputMaybe<MissionMutation>;
  what_we_do?: InputMaybe<What_We_DoMutation>;
  events?: InputMaybe<EventsMutation>;
  support?: InputMaybe<SupportMutation>;
  contact_intro?: InputMaybe<Contact_IntroMutation>;
  contact?: InputMaybe<ContactMutation>;
  donation?: InputMaybe<DonationMutation>;
  board?: InputMaybe<BoardMutation>;
  staff?: InputMaybe<StaffMutation>;
};

export type HeroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subheadline?: InputMaybe<Scalars['String']['input']>;
  cta_primary_text?: InputMaybe<Scalars['String']['input']>;
  cta_primary_link?: InputMaybe<Scalars['String']['input']>;
  cta_secondary_text?: InputMaybe<Scalars['String']['input']>;
  cta_secondary_link?: InputMaybe<Scalars['String']['input']>;
  hero_meta?: InputMaybe<Scalars['String']['input']>;
};

export type Hero_CardMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date_label?: InputMaybe<Scalars['String']['input']>;
  time_label?: InputMaybe<Scalars['String']['input']>;
  location_label?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  image_alt?: InputMaybe<Scalars['String']['input']>;
  ticket_url?: InputMaybe<Scalars['String']['input']>;
};

export type MissionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body_1?: InputMaybe<Scalars['String']['input']>;
  body_2?: InputMaybe<Scalars['String']['input']>;
};

export type What_We_DoMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  card_1_title?: InputMaybe<Scalars['String']['input']>;
  card_1_body?: InputMaybe<Scalars['String']['input']>;
  card_2_title?: InputMaybe<Scalars['String']['input']>;
  card_2_body?: InputMaybe<Scalars['String']['input']>;
  card_3_title?: InputMaybe<Scalars['String']['input']>;
  card_3_body?: InputMaybe<Scalars['String']['input']>;
};

export type EventsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  bullet_1?: InputMaybe<Scalars['String']['input']>;
  bullet_2?: InputMaybe<Scalars['String']['input']>;
  bullet_3?: InputMaybe<Scalars['String']['input']>;
  footer_note?: InputMaybe<Scalars['String']['input']>;
  featured_card_title?: InputMaybe<Scalars['String']['input']>;
  featured_card_intro?: InputMaybe<Scalars['String']['input']>;
  featured_card_body?: InputMaybe<Scalars['String']['input']>;
  featured_card_wexler_note?: InputMaybe<Scalars['String']['input']>;
  featured_card_gofundme_label?: InputMaybe<Scalars['String']['input']>;
  featured_card_gofundme_url?: InputMaybe<Scalars['String']['input']>;
  featured_card_tickets_label?: InputMaybe<Scalars['String']['input']>;
  featured_card_tickets_url?: InputMaybe<Scalars['String']['input']>;
};

export type SupportMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  bullet_1?: InputMaybe<Scalars['String']['input']>;
  bullet_2?: InputMaybe<Scalars['String']['input']>;
  bullet_3?: InputMaybe<Scalars['String']['input']>;
  bullet_4?: InputMaybe<Scalars['String']['input']>;
  card_title?: InputMaybe<Scalars['String']['input']>;
  card_body?: InputMaybe<Scalars['String']['input']>;
  card_link_label?: InputMaybe<Scalars['String']['input']>;
  card_link_url?: InputMaybe<Scalars['String']['input']>;
};

export type Contact_IntroMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  mailing_name?: InputMaybe<Scalars['String']['input']>;
  mailing_street?: InputMaybe<Scalars['String']['input']>;
  mailing_city?: InputMaybe<Scalars['String']['input']>;
};

export type DonationMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type BoardMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type BoardMutation = {
  members?: InputMaybe<Array<InputMaybe<BoardMembersMutation>>>;
};

export type StaffMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type StaffMutation = {
  members?: InputMaybe<Array<InputMaybe<StaffMembersMutation>>>;
};

export type HeroPartsFragment = { __typename: 'Hero', headline: string, subheadline?: string | null, cta_primary_text?: string | null, cta_primary_link?: string | null, cta_secondary_text?: string | null, cta_secondary_link?: string | null, hero_meta?: string | null };

export type Hero_CardPartsFragment = { __typename: 'Hero_card', title?: string | null, date_label?: string | null, time_label?: string | null, location_label?: string | null, description?: string | null, image?: string | null, image_alt?: string | null, ticket_url?: string | null };

export type MissionPartsFragment = { __typename: 'Mission', heading?: string | null, body_1?: string | null, body_2?: string | null };

export type What_We_DoPartsFragment = { __typename: 'What_we_do', heading?: string | null, card_1_title?: string | null, card_1_body?: string | null, card_2_title?: string | null, card_2_body?: string | null, card_3_title?: string | null, card_3_body?: string | null };

export type EventsPartsFragment = { __typename: 'Events', heading?: string | null, intro?: string | null, bullet_1?: string | null, bullet_2?: string | null, bullet_3?: string | null, footer_note?: string | null, featured_card_title?: string | null, featured_card_intro?: string | null, featured_card_body?: string | null, featured_card_wexler_note?: string | null, featured_card_gofundme_label?: string | null, featured_card_gofundme_url?: string | null, featured_card_tickets_label?: string | null, featured_card_tickets_url?: string | null };

export type SupportPartsFragment = { __typename: 'Support', heading?: string | null, intro?: string | null, bullet_1?: string | null, bullet_2?: string | null, bullet_3?: string | null, bullet_4?: string | null, card_title?: string | null, card_body?: string | null, card_link_label?: string | null, card_link_url?: string | null };

export type Contact_IntroPartsFragment = { __typename: 'Contact_intro', heading?: string | null, intro?: string | null };

export type ContactPartsFragment = { __typename: 'Contact', email?: string | null, phone?: string | null, facebook?: string | null, instagram?: string | null, linkedin?: string | null, mailing_name?: string | null, mailing_street?: string | null, mailing_city?: string | null };

export type DonationPartsFragment = { __typename: 'Donation', url?: string | null, label?: string | null };

export type BoardPartsFragment = { __typename: 'Board', members?: Array<{ __typename: 'BoardMembers', name: string, title?: string | null, image?: string | null } | null> | null };

export type StaffPartsFragment = { __typename: 'Staff', members?: Array<{ __typename: 'StaffMembers', name: string, title?: string | null, image?: string | null } | null> | null };

export type HeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeroQuery = { __typename?: 'Query', hero: { __typename: 'Hero', id: string, headline: string, subheadline?: string | null, cta_primary_text?: string | null, cta_primary_link?: string | null, cta_secondary_text?: string | null, cta_secondary_link?: string | null, hero_meta?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
}>;


export type HeroConnectionQuery = { __typename?: 'Query', heroConnection: { __typename?: 'HeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeroConnectionEdges', cursor: string, node?: { __typename: 'Hero', id: string, headline: string, subheadline?: string | null, cta_primary_text?: string | null, cta_primary_link?: string | null, cta_secondary_text?: string | null, cta_secondary_link?: string | null, hero_meta?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Hero_CardQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Hero_CardQuery = { __typename?: 'Query', hero_card: { __typename: 'Hero_card', id: string, title?: string | null, date_label?: string | null, time_label?: string | null, location_label?: string | null, description?: string | null, image?: string | null, image_alt?: string | null, ticket_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Hero_CardConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Hero_CardFilter>;
}>;


export type Hero_CardConnectionQuery = { __typename?: 'Query', hero_cardConnection: { __typename?: 'Hero_cardConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Hero_cardConnectionEdges', cursor: string, node?: { __typename: 'Hero_card', id: string, title?: string | null, date_label?: string | null, time_label?: string | null, location_label?: string | null, description?: string | null, image?: string | null, image_alt?: string | null, ticket_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MissionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MissionQuery = { __typename?: 'Query', mission: { __typename: 'Mission', id: string, heading?: string | null, body_1?: string | null, body_2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MissionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MissionFilter>;
}>;


export type MissionConnectionQuery = { __typename?: 'Query', missionConnection: { __typename?: 'MissionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MissionConnectionEdges', cursor: string, node?: { __typename: 'Mission', id: string, heading?: string | null, body_1?: string | null, body_2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type What_We_DoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type What_We_DoQuery = { __typename?: 'Query', what_we_do: { __typename: 'What_we_do', id: string, heading?: string | null, card_1_title?: string | null, card_1_body?: string | null, card_2_title?: string | null, card_2_body?: string | null, card_3_title?: string | null, card_3_body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type What_We_DoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<What_We_DoFilter>;
}>;


export type What_We_DoConnectionQuery = { __typename?: 'Query', what_we_doConnection: { __typename?: 'What_we_doConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'What_we_doConnectionEdges', cursor: string, node?: { __typename: 'What_we_do', id: string, heading?: string | null, card_1_title?: string | null, card_1_body?: string | null, card_2_title?: string | null, card_2_body?: string | null, card_3_title?: string | null, card_3_body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EventsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventsQuery = { __typename?: 'Query', events: { __typename: 'Events', id: string, heading?: string | null, intro?: string | null, bullet_1?: string | null, bullet_2?: string | null, bullet_3?: string | null, footer_note?: string | null, featured_card_title?: string | null, featured_card_intro?: string | null, featured_card_body?: string | null, featured_card_wexler_note?: string | null, featured_card_gofundme_label?: string | null, featured_card_gofundme_url?: string | null, featured_card_tickets_label?: string | null, featured_card_tickets_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
}>;


export type EventsConnectionQuery = { __typename?: 'Query', eventsConnection: { __typename?: 'EventsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventsConnectionEdges', cursor: string, node?: { __typename: 'Events', id: string, heading?: string | null, intro?: string | null, bullet_1?: string | null, bullet_2?: string | null, bullet_3?: string | null, footer_note?: string | null, featured_card_title?: string | null, featured_card_intro?: string | null, featured_card_body?: string | null, featured_card_wexler_note?: string | null, featured_card_gofundme_label?: string | null, featured_card_gofundme_url?: string | null, featured_card_tickets_label?: string | null, featured_card_tickets_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SupportQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SupportQuery = { __typename?: 'Query', support: { __typename: 'Support', id: string, heading?: string | null, intro?: string | null, bullet_1?: string | null, bullet_2?: string | null, bullet_3?: string | null, bullet_4?: string | null, card_title?: string | null, card_body?: string | null, card_link_label?: string | null, card_link_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SupportConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SupportFilter>;
}>;


export type SupportConnectionQuery = { __typename?: 'Query', supportConnection: { __typename?: 'SupportConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SupportConnectionEdges', cursor: string, node?: { __typename: 'Support', id: string, heading?: string | null, intro?: string | null, bullet_1?: string | null, bullet_2?: string | null, bullet_3?: string | null, bullet_4?: string | null, card_title?: string | null, card_body?: string | null, card_link_label?: string | null, card_link_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Contact_IntroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Contact_IntroQuery = { __typename?: 'Query', contact_intro: { __typename: 'Contact_intro', id: string, heading?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Contact_IntroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Contact_IntroFilter>;
}>;


export type Contact_IntroConnectionQuery = { __typename?: 'Query', contact_introConnection: { __typename?: 'Contact_introConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Contact_introConnectionEdges', cursor: string, node?: { __typename: 'Contact_intro', id: string, heading?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, email?: string | null, phone?: string | null, facebook?: string | null, instagram?: string | null, linkedin?: string | null, mailing_name?: string | null, mailing_street?: string | null, mailing_city?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, email?: string | null, phone?: string | null, facebook?: string | null, instagram?: string | null, linkedin?: string | null, mailing_name?: string | null, mailing_street?: string | null, mailing_city?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DonationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DonationQuery = { __typename?: 'Query', donation: { __typename: 'Donation', id: string, url?: string | null, label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DonationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DonationFilter>;
}>;


export type DonationConnectionQuery = { __typename?: 'Query', donationConnection: { __typename?: 'DonationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DonationConnectionEdges', cursor: string, node?: { __typename: 'Donation', id: string, url?: string | null, label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BoardQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BoardQuery = { __typename?: 'Query', board: { __typename: 'Board', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'BoardMembers', name: string, title?: string | null, image?: string | null } | null> | null } };

export type BoardConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BoardFilter>;
}>;


export type BoardConnectionQuery = { __typename?: 'Query', boardConnection: { __typename?: 'BoardConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BoardConnectionEdges', cursor: string, node?: { __typename: 'Board', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'BoardMembers', name: string, title?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export type StaffQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StaffQuery = { __typename?: 'Query', staff: { __typename: 'Staff', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'StaffMembers', name: string, title?: string | null, image?: string | null } | null> | null } };

export type StaffConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StaffFilter>;
}>;


export type StaffConnectionQuery = { __typename?: 'Query', staffConnection: { __typename?: 'StaffConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StaffConnectionEdges', cursor: string, node?: { __typename: 'Staff', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'StaffMembers', name: string, title?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  headline
  subheadline
  cta_primary_text
  cta_primary_link
  cta_secondary_text
  cta_secondary_link
  hero_meta
}
    `;
export const Hero_CardPartsFragmentDoc = gql`
    fragment Hero_cardParts on Hero_card {
  __typename
  title
  date_label
  time_label
  location_label
  description
  image
  image_alt
  ticket_url
}
    `;
export const MissionPartsFragmentDoc = gql`
    fragment MissionParts on Mission {
  __typename
  heading
  body_1
  body_2
}
    `;
export const What_We_DoPartsFragmentDoc = gql`
    fragment What_we_doParts on What_we_do {
  __typename
  heading
  card_1_title
  card_1_body
  card_2_title
  card_2_body
  card_3_title
  card_3_body
}
    `;
export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  heading
  intro
  bullet_1
  bullet_2
  bullet_3
  footer_note
  featured_card_title
  featured_card_intro
  featured_card_body
  featured_card_wexler_note
  featured_card_gofundme_label
  featured_card_gofundme_url
  featured_card_tickets_label
  featured_card_tickets_url
}
    `;
export const SupportPartsFragmentDoc = gql`
    fragment SupportParts on Support {
  __typename
  heading
  intro
  bullet_1
  bullet_2
  bullet_3
  bullet_4
  card_title
  card_body
  card_link_label
  card_link_url
}
    `;
export const Contact_IntroPartsFragmentDoc = gql`
    fragment Contact_introParts on Contact_intro {
  __typename
  heading
  intro
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  email
  phone
  facebook
  instagram
  linkedin
  mailing_name
  mailing_street
  mailing_city
}
    `;
export const DonationPartsFragmentDoc = gql`
    fragment DonationParts on Donation {
  __typename
  url
  label
}
    `;
export const BoardPartsFragmentDoc = gql`
    fragment BoardParts on Board {
  __typename
  members {
    __typename
    name
    title
    image
  }
}
    `;
export const StaffPartsFragmentDoc = gql`
    fragment StaffParts on Staff {
  __typename
  members {
    __typename
    name
    title
    image
  }
}
    `;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const Hero_CardDocument = gql`
    query hero_card($relativePath: String!) {
  hero_card(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Hero_cardParts
  }
}
    ${Hero_CardPartsFragmentDoc}`;
export const Hero_CardConnectionDocument = gql`
    query hero_cardConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Hero_cardFilter) {
  hero_cardConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Hero_cardParts
      }
    }
  }
}
    ${Hero_CardPartsFragmentDoc}`;
export const MissionDocument = gql`
    query mission($relativePath: String!) {
  mission(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MissionParts
  }
}
    ${MissionPartsFragmentDoc}`;
export const MissionConnectionDocument = gql`
    query missionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MissionFilter) {
  missionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MissionParts
      }
    }
  }
}
    ${MissionPartsFragmentDoc}`;
export const What_We_DoDocument = gql`
    query what_we_do($relativePath: String!) {
  what_we_do(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...What_we_doParts
  }
}
    ${What_We_DoPartsFragmentDoc}`;
export const What_We_DoConnectionDocument = gql`
    query what_we_doConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: What_we_doFilter) {
  what_we_doConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...What_we_doParts
      }
    }
  }
}
    ${What_We_DoPartsFragmentDoc}`;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export const SupportDocument = gql`
    query support($relativePath: String!) {
  support(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SupportParts
  }
}
    ${SupportPartsFragmentDoc}`;
export const SupportConnectionDocument = gql`
    query supportConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SupportFilter) {
  supportConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SupportParts
      }
    }
  }
}
    ${SupportPartsFragmentDoc}`;
export const Contact_IntroDocument = gql`
    query contact_intro($relativePath: String!) {
  contact_intro(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Contact_introParts
  }
}
    ${Contact_IntroPartsFragmentDoc}`;
export const Contact_IntroConnectionDocument = gql`
    query contact_introConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Contact_introFilter) {
  contact_introConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Contact_introParts
      }
    }
  }
}
    ${Contact_IntroPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const DonationDocument = gql`
    query donation($relativePath: String!) {
  donation(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DonationParts
  }
}
    ${DonationPartsFragmentDoc}`;
export const DonationConnectionDocument = gql`
    query donationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DonationFilter) {
  donationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DonationParts
      }
    }
  }
}
    ${DonationPartsFragmentDoc}`;
export const BoardDocument = gql`
    query board($relativePath: String!) {
  board(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BoardParts
  }
}
    ${BoardPartsFragmentDoc}`;
export const BoardConnectionDocument = gql`
    query boardConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BoardFilter) {
  boardConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BoardParts
      }
    }
  }
}
    ${BoardPartsFragmentDoc}`;
export const StaffDocument = gql`
    query staff($relativePath: String!) {
  staff(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StaffParts
  }
}
    ${StaffPartsFragmentDoc}`;
export const StaffConnectionDocument = gql`
    query staffConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StaffFilter) {
  staffConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StaffParts
      }
    }
  }
}
    ${StaffPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    hero_card(variables: Hero_CardQueryVariables, options?: C): Promise<{data: Hero_CardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Hero_CardQueryVariables, query: string}> {
        return requester<{data: Hero_CardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Hero_CardQueryVariables, query: string}, Hero_CardQueryVariables>(Hero_CardDocument, variables, options);
      },
    hero_cardConnection(variables?: Hero_CardConnectionQueryVariables, options?: C): Promise<{data: Hero_CardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Hero_CardConnectionQueryVariables, query: string}> {
        return requester<{data: Hero_CardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Hero_CardConnectionQueryVariables, query: string}, Hero_CardConnectionQueryVariables>(Hero_CardConnectionDocument, variables, options);
      },
    mission(variables: MissionQueryVariables, options?: C): Promise<{data: MissionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionQueryVariables, query: string}> {
        return requester<{data: MissionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionQueryVariables, query: string}, MissionQueryVariables>(MissionDocument, variables, options);
      },
    missionConnection(variables?: MissionConnectionQueryVariables, options?: C): Promise<{data: MissionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionConnectionQueryVariables, query: string}> {
        return requester<{data: MissionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionConnectionQueryVariables, query: string}, MissionConnectionQueryVariables>(MissionConnectionDocument, variables, options);
      },
    what_we_do(variables: What_We_DoQueryVariables, options?: C): Promise<{data: What_We_DoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: What_We_DoQueryVariables, query: string}> {
        return requester<{data: What_We_DoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: What_We_DoQueryVariables, query: string}, What_We_DoQueryVariables>(What_We_DoDocument, variables, options);
      },
    what_we_doConnection(variables?: What_We_DoConnectionQueryVariables, options?: C): Promise<{data: What_We_DoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: What_We_DoConnectionQueryVariables, query: string}> {
        return requester<{data: What_We_DoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: What_We_DoConnectionQueryVariables, query: string}, What_We_DoConnectionQueryVariables>(What_We_DoConnectionDocument, variables, options);
      },
    events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      },
    support(variables: SupportQueryVariables, options?: C): Promise<{data: SupportQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportQueryVariables, query: string}> {
        return requester<{data: SupportQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportQueryVariables, query: string}, SupportQueryVariables>(SupportDocument, variables, options);
      },
    supportConnection(variables?: SupportConnectionQueryVariables, options?: C): Promise<{data: SupportConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportConnectionQueryVariables, query: string}> {
        return requester<{data: SupportConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportConnectionQueryVariables, query: string}, SupportConnectionQueryVariables>(SupportConnectionDocument, variables, options);
      },
    contact_intro(variables: Contact_IntroQueryVariables, options?: C): Promise<{data: Contact_IntroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Contact_IntroQueryVariables, query: string}> {
        return requester<{data: Contact_IntroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Contact_IntroQueryVariables, query: string}, Contact_IntroQueryVariables>(Contact_IntroDocument, variables, options);
      },
    contact_introConnection(variables?: Contact_IntroConnectionQueryVariables, options?: C): Promise<{data: Contact_IntroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Contact_IntroConnectionQueryVariables, query: string}> {
        return requester<{data: Contact_IntroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Contact_IntroConnectionQueryVariables, query: string}, Contact_IntroConnectionQueryVariables>(Contact_IntroConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    donation(variables: DonationQueryVariables, options?: C): Promise<{data: DonationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DonationQueryVariables, query: string}> {
        return requester<{data: DonationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DonationQueryVariables, query: string}, DonationQueryVariables>(DonationDocument, variables, options);
      },
    donationConnection(variables?: DonationConnectionQueryVariables, options?: C): Promise<{data: DonationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DonationConnectionQueryVariables, query: string}> {
        return requester<{data: DonationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DonationConnectionQueryVariables, query: string}, DonationConnectionQueryVariables>(DonationConnectionDocument, variables, options);
      },
    board(variables: BoardQueryVariables, options?: C): Promise<{data: BoardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardQueryVariables, query: string}> {
        return requester<{data: BoardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardQueryVariables, query: string}, BoardQueryVariables>(BoardDocument, variables, options);
      },
    boardConnection(variables?: BoardConnectionQueryVariables, options?: C): Promise<{data: BoardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardConnectionQueryVariables, query: string}> {
        return requester<{data: BoardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardConnectionQueryVariables, query: string}, BoardConnectionQueryVariables>(BoardConnectionDocument, variables, options);
      },
    staff(variables: StaffQueryVariables, options?: C): Promise<{data: StaffQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StaffQueryVariables, query: string}> {
        return requester<{data: StaffQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StaffQueryVariables, query: string}, StaffQueryVariables>(StaffDocument, variables, options);
      },
    staffConnection(variables?: StaffConnectionQueryVariables, options?: C): Promise<{data: StaffConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StaffConnectionQueryVariables, query: string}> {
        return requester<{data: StaffConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StaffConnectionQueryVariables, query: string}, StaffConnectionQueryVariables>(StaffConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/f20ee16d-b53a-4382-bff0-7fe8adf96472/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  