import {SchemaTypeDefinition} from 'sanity'

export const schemaTypes: SchemaTypeDefinition[] = [
  {
    name: 'hero',
    title: 'Homepage – Hero',
    type: 'document',
    icon: () => '🏠',
    description: 'The main banner at the top of the homepage — headline, subheadline, and call-to-action buttons.',
    fields: [
      {
        name: 'headline',
        title: 'Headline',
        type: 'string',
        description: 'The large bold text at the top of the page. Keep it concise — one or two sentences max.',
        validation: (R: any) => R.required(),
      },
      {
        name: 'subheadline',
        title: 'Subheadline',
        type: 'text',
        rows: 3,
        description: 'Supporting text beneath the headline. Explains the mission in a little more detail.',
      },
      {
        name: 'cta_primary_text',
        title: 'Primary Button Text',
        type: 'string',
        description: 'Label on the main call-to-action button, e.g. "Ways to Give & Help".',
      },
      {
        name: 'cta_primary_link',
        title: 'Primary Button Link',
        type: 'string',
        description: 'Where the primary button goes. Use #section-id to scroll down the page, or a full URL.',
      },
      {
        name: 'cta_secondary_text',
        title: 'Secondary Button Text',
        type: 'string',
        description: 'Label on the secondary button, e.g. "Follow on Facebook".',
      },
      {
        name: 'cta_secondary_link',
        title: 'Secondary Button Link',
        type: 'string',
        description: 'Where the secondary button goes. Usually a social media URL.',
      },
      {
        name: 'hero_meta',
        title: 'Meta Text',
        type: 'text',
        rows: 2,
        description: 'Small supporting text shown below the buttons. Used for a brief impact statement.',
      },
    ],
  },
  {
    name: 'hero_card',
    title: 'Homepage – Hero Card',
    type: 'document',
    icon: () => '📌',
    description: 'The featured event card displayed alongside the hero banner.',
    fields: [
      {
        name: 'title',
        title: 'Event Title',
        type: 'string',
        description: 'Name of the featured event, e.g. "Winter Gala 2025".',
      },
      {
        name: 'date_label',
        title: 'Date',
        type: 'string',
        description: 'Display date for the event, e.g. "Saturday, December 14, 2025".',
      },
      {
        name: 'time_label',
        title: 'Time',
        type: 'string',
        description: 'Display time for the event, e.g. "6:00 PM – 10:00 PM".',
      },
      {
        name: 'location_label',
        title: 'Location',
        type: 'string',
        description: 'Venue name and/or address shown on the card.',
      },
      {
        name: 'description',
        title: 'Description',
        type: 'text',
        rows: 3,
        description: 'Short description of the event shown on the card.',
      },
      {
        name: 'image',
        title: 'Image',
        type: 'image',
        options: {hotspot: true},
        description: 'Photo shown on the event card. Use a landscape image for best results.',
      },
      {
        name: 'image_alt',
        title: 'Image Alt Text',
        type: 'string',
        description: 'Brief description of the image for screen readers and accessibility, e.g. "Gala dinner tables set up at Salvatore\'s".',
      },
      {
        name: 'ticket_url',
        title: 'Ticket URL',
        type: 'string',
        description: 'Link to purchase tickets or register for the event.',
      },
    ],
  },
  {
    name: 'mission',
    title: 'Homepage – Mission',
    type: 'document',
    icon: () => '💜',
    description: 'The mission statement section on the homepage.',
    fields: [
      {
        name: 'heading',
        title: 'Heading',
        type: 'string',
        description: 'Section heading, e.g. "Our Mission".',
      },
      {
        name: 'body_1',
        title: 'Body Paragraph 1',
        type: 'text',
        rows: 4,
        description: 'First paragraph of the mission statement.',
      },
      {
        name: 'body_2',
        title: 'Body Paragraph 2',
        type: 'text',
        rows: 4,
        description: 'Second paragraph — optional additional context or elaboration.',
      },
    ],
  },
  {
    name: 'what_we_do',
    title: 'Homepage – What We Do',
    type: 'document',
    icon: () => '🤝',
    description: 'The three-card "What We Do" section on the homepage.',
    fields: [
      {
        name: 'heading',
        title: 'Section Heading',
        type: 'string',
        description: 'Title above the three cards, e.g. "What We Do".',
      },
      {
        name: 'card_1_title',
        title: 'Card 1 – Title',
        type: 'string',
        description: 'Heading for the first card.',
      },
      {
        name: 'card_1_body',
        title: 'Card 1 – Body',
        type: 'text',
        rows: 3,
        description: 'Description text inside the first card.',
      },
      {
        name: 'card_2_title',
        title: 'Card 2 – Title',
        type: 'string',
        description: 'Heading for the second card.',
      },
      {
        name: 'card_2_body',
        title: 'Card 2 – Body',
        type: 'text',
        rows: 3,
        description: 'Description text inside the second card.',
      },
      {
        name: 'card_3_title',
        title: 'Card 3 – Title',
        type: 'string',
        description: 'Heading for the third card.',
      },
      {
        name: 'card_3_body',
        title: 'Card 3 – Body',
        type: 'text',
        rows: 3,
        description: 'Description text inside the third card.',
      },
    ],
  },
  {
    name: 'events',
    title: 'Section – Events',
    type: 'document',
    icon: () => '🎉',
    description: 'The Events section — intro text, bullet points, and the featured event card.',
    fields: [
      {
        name: 'heading',
        title: 'Section Heading',
        type: 'string',
        description: 'Title of the events section, e.g. "Events".',
      },
      {
        name: 'intro',
        title: 'Intro Text',
        type: 'text',
        rows: 3,
        description: 'Opening paragraph describing the types of events Abbie\'s Angels hosts.',
      },
      {
        name: 'bullet_1',
        title: 'Bullet 1',
        type: 'string',
        description: 'First bullet point describing an event type or activity.',
      },
      {
        name: 'bullet_2',
        title: 'Bullet 2',
        type: 'string',
        description: 'Second bullet point.',
      },
      {
        name: 'bullet_3',
        title: 'Bullet 3',
        type: 'string',
        description: 'Third bullet point.',
      },
      {
        name: 'footer_note',
        title: 'Footer Note',
        type: 'text',
        rows: 2,
        description: 'Small note at the bottom of the section, e.g. directing visitors to social media for updates.',
      },
      {
        name: 'featured_card_title',
        title: 'Featured Card – Title',
        type: 'string',
        description: 'Heading on the featured event card, e.g. "Get Gala Tickets".',
      },
      {
        name: 'featured_card_intro',
        title: 'Featured Card – Intro',
        type: 'text',
        rows: 2,
        description: 'Short intro line on the featured card — venue, vibe, one sentence.',
      },
      {
        name: 'featured_card_body',
        title: 'Featured Card – Body',
        type: 'text',
        rows: 4,
        description: 'Main body of the featured card. This is where the family story or event details go.',
      },
      {
        name: 'featured_card_wexler_note',
        title: 'Featured Card – Personal Note',
        type: 'text',
        rows: 2,
        description: 'Optional personal note from a board member connecting them to the featured family.',
      },
      {
        name: 'featured_card_gofundme_label',
        title: 'GoFundMe – Button Label',
        type: 'string',
        description: 'Text on the GoFundMe donation link, e.g. "Donate to Chelsea\'s Journey to Health".',
      },
      {
        name: 'featured_card_gofundme_url',
        title: 'GoFundMe – URL',
        type: 'string',
        description: 'Full URL to the GoFundMe campaign page.',
      },
      {
        name: 'featured_card_tickets_label',
        title: 'Tickets – Button Label',
        type: 'string',
        description: 'Text on the ticket purchase link.',
      },
      {
        name: 'featured_card_tickets_url',
        title: 'Tickets – URL',
        type: 'string',
        description: 'Full URL to the ticketing page, e.g. Auctria.',
      },
    ],
  },
  {
    name: 'support',
    title: 'Section – Ways to Help',
    type: 'document',
    icon: () => '💛',
    description: 'The "Ways to Give & Help" section with bullet points and a donation card.',
    fields: [
      {
        name: 'heading',
        title: 'Section Heading',
        type: 'string',
        description: 'Title of this section, e.g. "Ways to Give & Help".',
      },
      {
        name: 'intro',
        title: 'Intro Text',
        type: 'text',
        rows: 3,
        description: 'Opening paragraph explaining how visitors can support the organization.',
      },
      {
        name: 'bullet_1',
        title: 'Bullet 1',
        type: 'string',
        description: 'First way to help, e.g. "Donate directly through GoFundMe".',
      },
      {
        name: 'bullet_2',
        title: 'Bullet 2',
        type: 'string',
        description: 'Second way to help.',
      },
      {
        name: 'bullet_3',
        title: 'Bullet 3',
        type: 'string',
        description: 'Third way to help.',
      },
      {
        name: 'bullet_4',
        title: 'Bullet 4',
        type: 'string',
        description: 'Fourth way to help.',
      },
      {
        name: 'card_title',
        title: 'Card – Title',
        type: 'string',
        description: 'Heading on the support card, e.g. "Make a Difference Today".',
      },
      {
        name: 'card_body',
        title: 'Card – Body',
        type: 'text',
        rows: 3,
        description: 'Supporting text inside the card encouraging action.',
      },
      {
        name: 'card_link_label',
        title: 'Card – Link Label',
        type: 'string',
        description: 'Text on the card\'s action link or button.',
      },
      {
        name: 'card_link_url',
        title: 'Card – Link URL',
        type: 'string',
        description: 'URL the card button points to, usually the donation page.',
      },
    ],
  },
  {
    name: 'contact_intro',
    title: 'Section – Contact Intro',
    type: 'document',
    icon: () => '✉️',
    description: 'Heading and intro text shown above the contact form.',
    fields: [
      {
        name: 'heading',
        title: 'Heading',
        type: 'string',
        description: 'Section heading, e.g. "Get in Touch".',
      },
      {
        name: 'intro',
        title: 'Intro Text',
        type: 'text',
        rows: 3,
        description: 'A welcoming sentence or two inviting visitors to reach out.',
      },
    ],
  },
  {
    name: 'contact',
    title: 'Settings – Contact',
    type: 'document',
    icon: () => '📋',
    description: 'Global contact info used in the footer and contact section — update here and it changes site-wide.',
    fields: [
      {
        name: 'email',
        title: 'Email Address',
        type: 'string',
        description: 'Main contact email shown on the site.',
      },
      {
        name: 'phone',
        title: 'Phone Number',
        type: 'string',
        description: 'Contact phone number. Leave blank if not publicly listed.',
      },
      {
        name: 'facebook',
        title: 'Facebook URL',
        type: 'string',
        description: 'Full URL to the Facebook page, e.g. https://www.facebook.com/...',
      },
      {
        name: 'instagram',
        title: 'Instagram URL',
        type: 'string',
        description: 'Full URL to the Instagram profile.',
      },
      {
        name: 'linkedin',
        title: 'LinkedIn URL',
        type: 'string',
        description: 'Full URL to the LinkedIn page, if applicable.',
      },
      {
        name: 'mailing_name',
        title: 'Mailing Name',
        type: 'string',
        description: 'Organization name as it appears on the mailing address.',
      },
      {
        name: 'mailing_street',
        title: 'Mailing Street',
        type: 'string',
        description: 'Street address or P.O. Box for mail.',
      },
      {
        name: 'mailing_city',
        title: 'Mailing City',
        type: 'string',
        description: 'City, state, and ZIP for the mailing address.',
      },
    ],
  },
  {
    name: 'donation',
    title: 'Settings – Donation',
    type: 'document',
    icon: () => '💰',
    description: 'Controls the persistent Donate button that appears in the header and footer.',
    fields: [
      {
        name: 'url',
        title: 'Donation URL',
        type: 'string',
        description: 'Where the Donate button sends visitors — usually GoFundMe or Donorbox.',
        validation: (R: any) => R.required(),
      },
      {
        name: 'label',
        title: 'Donation Button Label',
        type: 'string',
        description: 'Text on the button itself, e.g. "Donate Now".',
        validation: (R: any) => R.required(),
      },
    ],
  },
  {
    name: 'board',
    title: 'Team – Board Members',
    type: 'document',
    icon: () => '👥',
    description: 'List of board members shown on the site. Add, remove, or reorder as needed.',
    fields: [
      {
        name: 'members',
        title: 'Board Members',
        type: 'array',
        description: 'Each entry is one board member. Drag to reorder.',
        of: [{
          type: 'object',
          preview: {select: {title: 'name', subtitle: 'title'}},
          fields: [
            {
              name: 'name',
              title: 'Full Name',
              type: 'string',
              description: 'Board member\'s full name.',
              validation: (R: any) => R.required(),
            },
            {
              name: 'title',
              title: 'Title / Role',
              type: 'string',
              description: 'Their role on the board, e.g. "President" or "Treasurer".',
            },
            {
              name: 'image',
              title: 'Photo',
              type: 'image',
              options: {hotspot: true},
              description: 'Headshot or photo. Square images work best.',
            },
          ],
        }],
      },
    ],
  },
  {
    name: 'staff',
    title: 'Team – Staff & Partners',
    type: 'document',
    icon: () => '🌟',
    description: 'List of staff members and partners shown on the site.',
    fields: [
      {
        name: 'members',
        title: 'Staff & Partners',
        type: 'array',
        description: 'Each entry is one staff member or partner. Drag to reorder.',
        of: [{
          type: 'object',
          preview: {select: {title: 'name', subtitle: 'title'}},
          fields: [
            {
              name: 'name',
              title: 'Full Name',
              type: 'string',
              description: 'Staff member\'s full name.',
              validation: (R: any) => R.required(),
            },
            {
              name: 'title',
              title: 'Title / Role',
              type: 'string',
              description: 'Their role or relationship to the organization.',
            },
            {
              name: 'image',
              title: 'Photo',
              type: 'image',
              options: {hotspot: true},
              description: 'Headshot or photo. Square images work best.',
            },
          ],
        }],
      },
    ],
  },
]
