import {SchemaTypeDefinition} from 'sanity'

export const schemaTypes: SchemaTypeDefinition[] = [
  {
    name: 'hero',
    title: 'Homepage – Hero',
    type: 'document',
    icon: () => '🏠',
    description: 'The main banner at the top of the homepage — headline, subheadline, and call-to-action buttons.',
    fields: [
      {
        name: 'headline',
        title: 'Headline',
        type: 'string',
        description: 'The large bold text at the top of the page. Keep it concise — one or two sentences max.',
        validation: (R: any) => R.required(),
      },
      {
        name: 'subheadline',
        title: 'Subheadline',
        type: 'text',
        rows: 3,
        description: 'Supporting text beneath the headline. Explains the mission in a little more detail.',
      },
      {
        name: 'cta_primary_text',
        title: 'Primary Button Text',
        type: 'string',
        description: 'Label on the main call-to-action button, e.g. "Ways to Give & Help".',
      },
      {
        name: 'cta_primary_link',
        title: 'Primary Button Link',
        type: 'string',
        description: 'Where the primary button goes. Use #section-id to scroll down the page, or a full URL.',
      },
      {
        name: 'cta_secondary_text',
        title: 'Secondary Button Text',
        type: 'string',
        description: 'Label on the secondary button, e.g. "Follow on Facebook".',
      },
      {
        name: 'cta_secondary_link',
        title: 'Secondary Button Link',
        type: 'string',
        description: 'Where the secondary button goes. Usually a social media URL.',
      },
      {
        name: 'hero_meta',
        title: 'Meta Text',
        type: 'text',
        rows: 2,
        description: 'Small supporting text shown below the buttons. Used for a brief impact statement.',
      },
    ],
  },
  {
    name: 'hero_card',
    title: 'Homepage – Hero Card',
    type: 'document',
    icon: () => '📌',
    description: 'The featured event card displayed alongside the hero banner. Note: this is now auto-populated from whichever Event has "Featured" checked. Only edit here if you need a manual override.',
    fields: [
      {
        name: 'title',
        title: 'Event Title',
        type: 'string',
        description: 'Name of the featured event, e.g. "Winter Gala 2025".',
      },
      {
        name: 'date_label',
        title: 'Date',
        type: 'string',
        description: 'Display date for the event, e.g. "Saturday, December 14, 2025".',
      },
      {
        name: 'time_label',
        title: 'Time',
        type: 'string',
        description: 'Display time for the event, e.g. "6:00 PM – 10:00 PM".',
      },
      {
        name: 'location_label',
        title: 'Location',
        type: 'string',
        description: 'Venue name and/or address shown on the card.',
      },
      {
        name: 'description',
        title: 'Description',
        type: 'text',
        rows: 3,
        description: 'Short description of the event shown on the card.',
      },
      {
        name: 'image',
        title: 'Image',
        type: 'image',
        options: {hotspot: true},
        description: 'Photo shown on the event card. Use a landscape image for best results.',
      },
      {
        name: 'image_alt',
        title: 'Image Alt Text',
        type: 'string',
        description: 'Brief description of the image for screen readers and accessibility.',
      },
      {
        name: 'ticket_url',
        title: 'Ticket URL',
        type: 'string',
        description: 'Link to purchase tickets or register for the event.',
      },
    ],
  },
  {
    name: 'event',
    title: 'Events – Event',
    type: 'document',
    icon: () => '🎟️',
    description: 'An individual event. Set "Published" to show it on the site. Set "Featured" to highlight it on the homepage hero.',
    fields: [
      {
        name: 'title',
        title: 'Event Title',
        type: 'string',
        description: 'Name of the event, e.g. "Winter Gala 2026".',
        validation: (R: any) => R.required(),
      },
      {
        name: 'date',
        title: 'Date',
        type: 'date',
        options: {dateFormat: 'MMMM D, YYYY'},
        description: 'Date of the event. Used for sorting and display.',
        validation: (R: any) => R.required(),
      },
      {
        name: 'date_label',
        title: 'Date Display Label',
        type: 'string',
        description: 'How the date appears on the site, e.g. "Saturday, December 14, 2026". Overrides the raw date if set.',
      },
      {
        name: 'time_label',
        title: 'Time',
        type: 'string',
        description: 'Display time for the event, e.g. "6:00 PM – 10:00 PM".',
      },
      {
        name: 'location',
        title: 'Location',
        type: 'string',
        description: 'Venue name and/or address.',
      },
      {
        name: 'description',
        title: 'Description',
        type: 'text',
        rows: 5,
        description: 'Full description of the event shown on the Events page.',
      },
      {
        name: 'image',
        title: 'Event Image',
        type: 'image',
        options: {hotspot: true},
        description: 'Photo for this event. Landscape images work best.',
      },
      {
        name: 'image_alt',
        title: 'Image Alt Text',
        type: 'string',
        description: 'Brief description of the image for accessibility.',
      },
      {
        name: 'ticket_url',
        title: 'Ticket / Registration URL',
        type: 'string',
        description: 'Link to purchase tickets or register. Leave blank if no tickets needed.',
      },
      {
        name: 'ticket_label',
        title: 'Ticket Button Label',
        type: 'string',
        description: 'Text on the ticket button, e.g. "Get Tickets" or "Register Now". Defaults to "Get Tickets" if blank.',
      },
      {
        name: 'published',
        title: 'Published',
        type: 'boolean',
        description: 'Turn on to show this event on the Events page. Turn off to hide it without deleting.',
        initialValue: false,
      },
      {
        name: 'featured',
        title: 'Featured on Homepage',
        type: 'boolean',
        description: 'Turn on to show this event in the homepage hero card. Only one event should be featured at a time.',
        initialValue: false,
      },
    ],
    preview: {
      select: {
        title: 'title',
        subtitle: 'date',
        published: 'published',
        featured: 'featured',
      },
      prepare({title, subtitle, published, featured}: any) {
        const flags = [published ? '✅ Published' : '🚫 Hidden', featured ? '⭐ Featured' : ''].filter(Boolean).join(' · ')
        return {title, subtitle: `${subtitle || ''} — ${flags}`}
      },
    },
  },
  {
    name: 'mission',
    title: 'Homepage – Mission',
    type: 'document',
    icon: () => '💜',
    description: 'The mission statement section on the homepage.',
    fields: [
      {
        name: 'heading',
        title: 'Heading',
        type: 'string',
        description: 'Section heading, e.g. "Our Mission".',
      },
      {
        name: 'body_1',
        title: 'Body Paragraph 1',
        type: 'text',
        rows: 4,
        description: 'First paragraph of the mission statement.',
      },
      {
        name: 'body_2',
        title: 'Body Paragraph 2',
        type: 'text',
        rows: 4,
        description: 'Second paragraph — optional additional context or elaboration.',
      },
    ],
  },
  {
    name: 'what_we_do',
    title: 'Homepage – What We Do',
    type: 'document',
    icon: () => '🤝',
    description: 'The three-card "What We Do" section on the homepage.',
    fields: [
      {
        name: 'heading',
        title: 'Section Heading',
        type: 'string',
        description: 'Title above the three cards, e.g. "What We Do".',
      },
      {
        name: 'card_1_title',
        title: 'Card 1 – Title',
        type: 'string',
        description: 'Heading for the first card.',
      },
      {
        name: 'card_1_body',
        title: 'Card 1 – Body',
        type: 'text',
        rows: 3,
        description: 'Description text inside the first card.',
      },
      {
        name: 'card_2_title',
        title: 'Card 2 – Title',
        type: 'string',
        description: 'Heading for the second card.',
      },
      {
        name: 'card_2_body',
        title: 'Card 2 – Body',
        type: 'text',
        rows: 3,
        description: 'Description text inside the second card.',
      },
      {
        name: 'card_3_title',
        title: 'Card 3 – Title',
        type: 'string',
        description: 'Heading for the third card.',
      },
      {
        name: 'card_3_body',
        title: 'Card 3 – Body',
        type: 'text',
        rows: 3,
        description: 'Description text inside the third card.',
      },
    ],
  },
  {
    name: 'events',
    title: 'Section – Events (Homepage)',
    type: 'document',
    icon: () => '🎉',
    description: 'The Events section intro text on the homepage. Individual events are now managed under "Events – Event".',
    fields: [
      {
        name: 'heading',
        title: 'Section Heading',
        type: 'string',
        description: 'Title of the events section, e.g. "Events".',
      },
      {
        name: 'intro',
        title: 'Intro Text',
        type: 'text',
        rows: 3,
        description: 'Opening paragraph describing the types of events Abbie\'s Angels hosts.',
      },
      {
        name: 'footer_note',
        title: 'Footer Note',
        type: 'text',
        rows: 2,
        description: 'Small note at the bottom of the section, e.g. directing visitors to social media for updates.',
      },
      {
        name: 'view_all_label',
        title: 'View All Button Label',
        type: 'string',
        description: 'Text on the "View All Events" link. Defaults to "View All Events →" if blank.',
      },
    ],
  },
  {
    name: 'support',
    title: 'Section – Ways to Help',
    type: 'document',
    icon: () => '💛',
    description: 'The "Ways to Give & Help" section with bullet points and a donation card.',
    fields: [
      {
        name: 'heading',
        title: 'Section Heading',
        type: 'string',
        description: 'Title of this section, e.g. "Ways to Give & Help".',
      },
      {
        name: 'intro',
        title: 'Intro Text',
        type: 'text',
        rows: 3,
        description: 'Opening paragraph explaining how visitors can support the organization.',
      },
      {
        name: 'bullet_1',
        title: 'Bullet 1',
        type: 'string',
        description: 'First way to help.',
      },
      {
        name: 'bullet_2',
        title: 'Bullet 2',
        type: 'string',
        description: 'Second way to help.',
      },
      {
        name: 'bullet_3',
        title: 'Bullet 3',
        type: 'string',
        description: 'Third way to help.',
      },
      {
        name: 'bullet_4',
        title: 'Bullet 4',
        type: 'string',
        description: 'Fourth way to help.',
      },
      {
        name: 'card_title',
        title: 'Card – Title',
        type: 'string',
        description: 'Heading on the support card.',
      },
      {
        name: 'card_body',
        title: 'Card – Body',
        type: 'text',
        rows: 3,
        description: 'Supporting text inside the card encouraging action.',
      },
      {
        name: 'card_link_label',
        title: 'Card – Link Label',
        type: 'string',
        description: 'Text on the card\'s action link or button.',
      },
      {
        name: 'card_link_url',
        title: 'Card – Link URL',
        type: 'string',
        description: 'URL the card button points to, usually the donation page.',
      },
    ],
  },
  {
    name: 'contact_intro',
    title: 'Section – Contact Intro',
    type: 'document',
    icon: () => '✉️',
    description: 'Heading and intro text shown above the contact form.',
    fields: [
      {
        name: 'heading',
        title: 'Heading',
        type: 'string',
        description: 'Section heading, e.g. "Get in Touch".',
      },
      {
        name: 'intro',
        title: 'Intro Text',
        type: 'text',
        rows: 3,
        description: 'A welcoming sentence or two inviting visitors to reach out.',
      },
    ],
  },
  {
    name: 'contact',
    title: 'Settings – Contact',
    type: 'document',
    icon: () => '📋',
    description: 'Global contact info used in the footer and contact section — update here and it changes site-wide.',
    fields: [
      {
        name: 'email',
        title: 'Email Address',
        type: 'string',
        description: 'Main contact email shown on the site.',
      },
      {
        name: 'phone',
        title: 'Phone Number',
        type: 'string',
        description: 'Contact phone number. Leave blank if not publicly listed.',
      },
      {
        name: 'facebook',
        title: 'Facebook URL',
        type: 'string',
        description: 'Full URL to the Facebook page.',
      },
      {
        name: 'instagram',
        title: 'Instagram URL',
        type: 'string',
        description: 'Full URL to the Instagram profile.',
      },
      {
        name: 'linkedin',
        title: 'LinkedIn URL',
        type: 'string',
        description: 'Full URL to the LinkedIn page, if applicable.',
      },
      {
        name: 'mailing_name',
        title: 'Mailing Name',
        type: 'string',
        description: 'Organization name as it appears on the mailing address.',
      },
      {
        name: 'mailing_street',
        title: 'Mailing Street',
        type: 'string',
        description: 'Street address or P.O. Box for mail.',
      },
      {
        name: 'mailing_city',
        title: 'Mailing City',
        type: 'string',
        description: 'City, state, and ZIP for the mailing address.',
      },
    ],
  },
  {
    name: 'donation',
    title: 'Settings – Donation',
    type: 'document',
    icon: () => '💰',
    description: 'Controls the persistent Donate button that appears in the header and footer.',
    fields: [
      {
        name: 'url',
        title: 'Donation URL',
        type: 'string',
        description: 'Where the Donate button sends visitors — usually GoFundMe or Donorbox.',
        validation: (R: any) => R.required(),
      },
      {
        name: 'label',
        title: 'Donation Button Label',
        type: 'string',
        description: 'Text on the button itself, e.g. "Donate Now".',
        validation: (R: any) => R.required(),
      },
    ],
  },
  {
    name: 'board',
    title: 'Team – Board Members',
    type: 'document',
    icon: () => '👥',
    description: 'List of board members shown on the site. Add, remove, or reorder as needed.',
    fields: [
      {
        name: 'members',
        title: 'Board Members',
        type: 'array',
        description: 'Each entry is one board member. Drag to reorder.',
        of: [{
          type: 'object',
          preview: {select: {title: 'name', subtitle: 'title'}},
          fields: [
            {
              name: 'name',
              title: 'Full Name',
              type: 'string',
              description: 'Board member\'s full name.',
              validation: (R: any) => R.required(),
            },
            {
              name: 'title',
              title: 'Title / Role',
              type: 'string',
              description: 'Their role on the board, e.g. "President" or "Treasurer".',
            },
            {
              name: 'image',
              title: 'Photo URL',
              type: 'string',
              description: 'URL to the photo. Images are hosted on the website — do not change unless replacing with a new upload.',
            },
          ],
        }],
      },
    ],
  },
  {
    name: 'staff',
    title: 'Team – Staff & Partners',
    type: 'document',
    icon: () => '🌟',
    description: 'List of staff members and partners shown on the site.',
    fields: [
      {
        name: 'members',
        title: 'Staff & Partners',
        type: 'array',
        description: 'Each entry is one staff member or partner. Drag to reorder.',
        of: [{
          type: 'object',
          preview: {select: {title: 'name', subtitle: 'title'}},
          fields: [
            {
              name: 'name',
              title: 'Full Name',
              type: 'string',
              description: 'Staff member\'s full name.',
              validation: (R: any) => R.required(),
            },
            {
              name: 'title',
              title: 'Title / Role',
              type: 'string',
              description: 'Their role or relationship to the organization.',
            },
            {
              name: 'image',
              title: 'Photo URL',
              type: 'string',
              description: 'URL to the photo. Images are hosted on the website — do not change unless replacing with a new upload.',
            },
          ],
        }],
      },
    ],
  },
]
