import {SchemaTypeDefinition} from 'sanity'

export const schemaTypes: SchemaTypeDefinition[] = [
  {
    name: 'hero',
    title: 'Homepage – Hero',
    type: 'document',
    icon: () => '🏠',
    description: 'The main banner at the top of the homepage — headline, subheadline, and call-to-action buttons.',
    fields: [
      { name: 'headline', title: 'Headline', type: 'string', description: 'The large bold text at the top of the page.', validation: (R: any) => R.required() },
      { name: 'subheadline', title: 'Subheadline', type: 'text', rows: 3, description: 'Supporting text beneath the headline.' },
      { name: 'cta_primary_text', title: 'Primary Button Text', type: 'string' },
      { name: 'cta_primary_link', title: 'Primary Button Link', type: 'string', description: 'Use #section-id to scroll, or a full URL.' },
      { name: 'cta_secondary_text', title: 'Secondary Button Text', type: 'string' },
      { name: 'cta_secondary_link', title: 'Secondary Button Link', type: 'string' },
      { name: 'hero_meta', title: 'Meta Text', type: 'text', rows: 2, description: 'Small impact statement shown below the buttons.' },
    ],
  },
  {
    name: 'hero_card',
    title: 'Homepage – Hero Card (Manual Override)',
    type: 'document',
    icon: () => '📌',
    description: 'Only used if no Event has "Featured on Homepage" checked. Otherwise the featured Event drives this card automatically.',
    fields: [
      { name: 'title', title: 'Event Title', type: 'string' },
      { name: 'date_label', title: 'Date', type: 'string' },
      { name: 'time_label', title: 'Time', type: 'string' },
      { name: 'location_label', title: 'Location', type: 'string' },
      { name: 'description', title: 'Description', type: 'text', rows: 3 },
      { name: 'image', title: 'Image', type: 'image', options: { hotspot: true } },
      { name: 'image_alt', title: 'Image Alt Text', type: 'string' },
      { name: 'ticket_url', title: 'Ticket URL', type: 'string' },
    ],
  },
  {
    name: 'event',
    title: 'Event',
    type: 'document',
    icon: () => '🎟️',
    description: 'An individual event. Toggle Published to show/hide. Toggle Featured to highlight on the homepage.',
    fields: [
      { name: 'title', title: 'Event Title', type: 'string', validation: (R: any) => R.required() },
      { name: 'date', title: 'Date', type: 'date', options: { dateFormat: 'MMMM D, YYYY' }, validation: (R: any) => R.required() },
      { name: 'date_label', title: 'Date Display Label', type: 'string', description: 'Friendly override, e.g. "Saturday, December 14, 2026". Leave blank to auto-format.' },
      { name: 'time_label', title: 'Time', type: 'string', description: 'e.g. "6:00 PM – 10:00 PM"' },
      { name: 'location', title: 'Location', type: 'string' },
      { name: 'description', title: 'Description', type: 'text', rows: 5 },
      { name: 'image', title: 'Event Image', type: 'image', options: { hotspot: true } },
      { name: 'image_alt', title: 'Image Alt Text', type: 'string' },
      { name: 'ticket_url', title: 'Ticket / Registration URL', type: 'string' },
      { name: 'ticket_label', title: 'Ticket Button Label', type: 'string', description: 'Defaults to "Get Tickets" if blank.' },
      { name: 'published', title: 'Published', type: 'boolean', description: 'Show on the Events page.', initialValue: false },
      { name: 'featured', title: 'Featured on Homepage', type: 'boolean', description: 'Show in the homepage hero card. Only one event should be featured at a time.', initialValue: false },
    ],
    preview: {
      select: { title: 'title', subtitle: 'date', published: 'published', featured: 'featured' },
      prepare({ title, subtitle, published, featured }: any) {
        const flags = [published ? '✅ Published' : '🚫 Hidden', featured ? '⭐ Featured' : ''].filter(Boolean).join(' · ')
        return { title, subtitle: `${subtitle || ''} — ${flags}` }
      },
    },
  },
  {
    name: 'mission',
    title: 'Homepage – Mission',
    type: 'document',
    icon: () => '💜',
    description: 'The mission statement section on the homepage.',
    fields: [
      { name: 'heading', title: 'Heading', type: 'string' },
      { name: 'body_1', title: 'Body Paragraph 1', type: 'text', rows: 4 },
      { name: 'body_2', title: 'Body Paragraph 2', type: 'text', rows: 4, description: 'Optional second paragraph.' },
    ],
  },
  {
    name: 'what_we_do',
    title: 'Homepage – What We Do',
    type: 'document',
    icon: () => '🤝',
    description: 'The three-card "What We Do" section on the homepage.',
    fields: [
      { name: 'heading', title: 'Section Heading', type: 'string' },
      { name: 'card_1_title', title: 'Card 1 – Title', type: 'string' },
      { name: 'card_1_body', title: 'Card 1 – Body', type: 'text', rows: 3 },
      { name: 'card_2_title', title: 'Card 2 – Title', type: 'string' },
      { name: 'card_2_body', title: 'Card 2 – Body', type: 'text', rows: 3 },
      { name: 'card_3_title', title: 'Card 3 – Title', type: 'string' },
      { name: 'card_3_body', title: 'Card 3 – Body', type: 'text', rows: 3 },
    ],
  },
  {
    name: 'events',
    title: 'Events – Page Settings',
    type: 'document',
    icon: () => '⚙️',
    description: 'Page heading and intro text shown at the top of the /events page. Individual events are managed separately.',
    fields: [
      { name: 'heading', title: 'Page Heading', type: 'string', description: 'e.g. "Events"' },
      { name: 'intro', title: 'Intro Text', type: 'text', rows: 3 },
      { name: 'footer_note', title: 'Footer Note', type: 'text', rows: 2, description: 'Optional note shown at the bottom of the events page.' },
      { name: 'view_all_label', title: 'View All Button Label', type: 'string', description: 'Text on the homepage "View All Events" link. Defaults to "View All Events →".' },
    ],
  },
  {
    name: 'support',
    title: 'Ways to Help',
    type: 'document',
    icon: () => '💛',
    description: 'The "Ways to Give & Help" section — bullet points and donation card.',
    fields: [
      { name: 'heading', title: 'Section Heading', type: 'string' },
      { name: 'intro', title: 'Intro Text', type: 'text', rows: 3 },
      { name: 'bullet_1', title: 'Bullet 1', type: 'string' },
      { name: 'bullet_2', title: 'Bullet 2', type: 'string' },
      { name: 'bullet_3', title: 'Bullet 3', type: 'string' },
      { name: 'bullet_4', title: 'Bullet 4', type: 'string' },
      { name: 'card_title', title: 'Card – Title', type: 'string' },
      { name: 'card_body', title: 'Card – Body', type: 'text', rows: 3 },
      { name: 'card_link_label', title: 'Card – Link Label', type: 'string' },
      { name: 'card_link_url', title: 'Card – Link URL', type: 'string' },
    ],
  },
  {
    name: 'contact',
    title: 'Contact',
    type: 'document',
    icon: () => '📧',
    description: 'Everything contact-related in one place — section heading, intro text, email, social links, and mailing address.',
    fields: [
      {
        name: 'heading',
        title: 'Section Heading',
        type: 'string',
        description: 'Heading shown above the contact cards on the homepage, e.g. "Get in Touch".',
      },
      {
        name: 'intro',
        title: 'Intro Text',
        type: 'text',
        rows: 3,
        description: 'A welcoming sentence or two inviting visitors to reach out.',
      },
      { name: 'email', title: 'Email Address', type: 'string' },
      { name: 'phone', title: 'Phone Number', type: 'string', description: 'Leave blank if not publicly listed.' },
      { name: 'facebook', title: 'Facebook URL', type: 'string' },
      { name: 'instagram', title: 'Instagram URL', type: 'string' },
      { name: 'linkedin', title: 'LinkedIn URL', type: 'string' },
      { name: 'mailing_name', title: 'Mailing Name', type: 'string' },
      { name: 'mailing_street', title: 'Mailing Street', type: 'string' },
      { name: 'mailing_city', title: 'Mailing City / State / ZIP', type: 'string' },
    ],
  },
  {
    name: 'donation',
    title: 'Donation Button',
    type: 'document',
    icon: () => '💰',
    description: 'Controls the Donate button that appears sitewide.',
    fields: [
      { name: 'url', title: 'Donation URL', type: 'string', description: 'Usually GoFundMe or Donorbox.', validation: (R: any) => R.required() },
      { name: 'label', title: 'Button Label', type: 'string', description: 'e.g. "Donate Now"', validation: (R: any) => R.required() },
    ],
  },
  {
    name: 'board',
    title: 'Team – Board Members',
    type: 'document',
    icon: () => '👥',
    description: 'Board members shown on the site. Add, remove, or drag to reorder.',
    fields: [
      {
        name: 'members', title: 'Board Members', type: 'array',
        of: [{
          type: 'object',
          preview: { select: { title: 'name', subtitle: 'title' } },
          fields: [
            { name: 'name', title: 'Full Name', type: 'string', validation: (R: any) => R.required() },
            { name: 'title', title: 'Title / Role', type: 'string' },
            { name: 'image', title: 'Photo URL', type: 'string' },
          ],
        }],
      },
    ],
  },
  {
    name: 'staff',
    title: 'Team – Staff & Partners',
    type: 'document',
    icon: () => '🌟',
    description: 'Staff and partners shown on the site. Add, remove, or drag to reorder.',
    fields: [
      {
        name: 'members', title: 'Staff & Partners', type: 'array',
        of: [{
          type: 'object',
          preview: { select: { title: 'name', subtitle: 'title' } },
          fields: [
            { name: 'name', title: 'Full Name', type: 'string', validation: (R: any) => R.required() },
            { name: 'title', title: 'Title / Role', type: 'string' },
            { name: 'image', title: 'Photo URL', type: 'string' },
          ],
        }],
      },
    ],
  },
]
