backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General"
        name: "general"
        file: "_data/settings.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
